lint:
    files_exist:
    - assets/nf-core-systemsgenetics/gemmaker_logo.png
    - docs/images/nf-core-systemsgenetics/gemmaker_logo.png
    - conf/igenomes.config
    files_unchanged:
    - .github/CONTRIBUTING.md
    - .github/ISSUE_TEMPLATE/bug_report.md
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/ISSUE_TEMPLATE/feature_request.md
    - .github/PULL_REQUEST_TEMPLATE.md
    - .github/workflows/branch.yml
    - assets/email_template.html
    - assets/email_template.txt
    - bin/scrape_software_versions.py
    - docs/README.md
    - assets/multiqc_config.yaml
    nextflow_config: false
