dist: xenial
language: python

jdk: openjdk8
python: 3.5

services:
  - docker

# Install all dependencies here.
install:
  - pip install -q pandas xmltodict
  - curl -fsSL get.nextflow.io | bash
  - mkdir -p ~/bin
  - cp nextflow ~/bin

# Commands here should determine whether the build fails or not.
script:
  # Run unit tests
  - python tests/retrieve_sra_metadata.py

  # Build the images.
  - make -C Dockerfiles

  # Run the workflow.
  - nextflow run main.nf -ansi-log false -profile travis
  - nextflow run main-e2e.nf -ansi-log false -profile travis
