dist: xenial
language: python

jdk: openjdk8
python: 3.5

services:
  - docker

# Install all dependencies here.
install:
  - pip install -q pandas xmltodict
  - curl -fsSL get.nextflow.io | bash
  - mkdir -p ~/bin
  - cp nextflow ~/bin

# Commands here should determine whether the build fails or not.
script:
  # Build the Docker images
  - make -C docker

  # Run unit tests
  - python tests/retrieve_sra_metadata.py

  # Run the example test
  - tests/run-example.sh
