FROM gemmaker/python:3.7-1.1

# Install MultiQC
RUN pip3 install https://github.com/ewels/MultiQC/archive/v1.7.zip \
  && pip3 install decorator>=4.3.0 && pip3 install networkx

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8
