FROM systemsgenetics/gemmaker:latest

RUN wget https://download.asperasoft.com/download/sw/client/3.9.1/ibm-aspera-desktopclient-3.9.1.168302-linux-64.deb

RUN dpkg -i ibm-aspera-desktopclient-3.9.1.168302-linux-64.deb
